# Generated by Django 5.2.8 on 2025-11-16 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplierID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tax_id",
                    models.CharField(
                        help_text="Número de Identificação Fiscal (9 dígitos)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIF deve ter 9 dígitos", regex="^[0-9]{9}$"
                            )
                        ],
                        verbose_name="NIF",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Pessoa de Contacto",
                    ),
                ),
                ("street_name", models.CharField(max_length=200, verbose_name="Rua")),
                (
                    "building_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Número"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Formato: 7600-000",
                        max_length=20,
                        verbose_name="Código Postal",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Região"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="CV",
                        help_text="Código ISO 3166-1 alpha-2 (ex: CV, PT)",
                        max_length=2,
                        verbose_name="País (Código ISO)",
                    ),
                ),
                (
                    "address_detail",
                    models.TextField(
                        blank=True,
                        help_text="Informações adicionais (apartamento, andar, etc.)",
                        null=True,
                        verbose_name="Detalhes de Morada",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telemóvel"
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Fax"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Conta Bancária",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=34, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="ex: 30 dias, Pronto pagamento",
                        max_length=100,
                        null=True,
                        verbose_name="Condições de Pagamento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "apps_supplier",
                "ordering": ["company_name"],
                "indexes": [
                    models.Index(
                        fields=["tax_id"], name="apps_suppli_tax_id_728f6d_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="apps_suppli_company_a85fc9_idx"
                    ),
                ],
            },
        ),
    ]
