# Generated by Django 5.2.7 on 2025-10-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='aapps_order',
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table='aapps_orderdetails',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='aapps_orderitem',
        ),
    ]
