# Generated by Django 5.2.7 on 2025-10-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table_alter_orderdetails_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='apps_order',
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table='apps_orderdetails',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='apps_orderitem',
        ),
    ]
