# Generated by Django 5.2.8 on 2025-11-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0003_alter_order_table_alter_orderdetails_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente registado (opcional - deixar vazio para vendas anônimas)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customers.customer",
                verbose_name="Cliente",
            ),
        ),
    ]
