# Generated by Django 5.2.7 on 2025-10-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='apps_payment',
        ),
    ]
