# Generated by Django 5.2.7 on 2025-11-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_table_alter_orderdetails_table_and_more'),
        ('payments', '0002_alter_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_paid', models.PositiveIntegerField(default=1, help_text='How many of this item were paid in this payment')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for this item in this payment', max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.orderitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_items', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Item',
                'verbose_name_plural': 'Payment Items',
                'db_table': 'apps_payment_item',
            },
        ),
    ]
