# Generated by Django 5.2.8 on 2025-11-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome do Cliente"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_tax_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="NIF do Cliente"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="hash_algorithm",
            field=models.CharField(
                default="SHA256", max_length=10, verbose_name="Algoritmo de Hash"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Fatura"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash for invoice integrity",
                max_length=256,
                null=True,
                verbose_name="Hash da Fatura",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_no",
            field=models.CharField(
                blank=True,
                help_text="Formato: SÉRIE/ANO/NÚMERO (ex: FT A/2025/00001)",
                max_length=60,
                null=True,
                unique=True,
                verbose_name="Número da Fatura",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("FT", "Fatura"),
                    ("NC", "Nota de Crédito"),
                    ("TV", "Talão de Venda"),
                    ("FR", "Fatura Recibo"),
                ],
                default="FT",
                max_length=10,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_signed",
            field=models.BooleanField(
                default=False,
                help_text="Se True, o documento não pode ser editado",
                verbose_name="Assinado",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="iud",
            field=models.CharField(
                blank=True,
                help_text="Identificador Único do Documento (45 caracteres)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="IUD",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="previous_invoice_hash",
            field=models.CharField(
                blank=True,
                help_text="Links invoices in a chain",
                max_length=256,
                null=True,
                verbose_name="Hash da Fatura Anterior",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="software_certificate_number",
            field=models.CharField(
                default="0",
                max_length=20,
                verbose_name="Número de Certificado do Software",
            ),
        ),
    ]
