# Generated by Django 5.2.8 on 2025-11-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_customer_name_payment_customer_tax_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="credit_note_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M01", "Mercadorias devolvidas"),
                    ("M02", "Erro de faturação"),
                    ("M03", "Anulação total do documento"),
                    ("M04", "Desconto"),
                    ("M05", "Devolução parcial"),
                    ("M99", "Outros motivos"),
                ],
                help_text="SAF-T CV IssueReasonCode (M01-M05, M99)",
                max_length=10,
                null=True,
                verbose_name="Motivo da Nota de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="referenced_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Original invoice that this credit note references (only for NC)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes",
                to="payments.payment",
                verbose_name="Documento Referenciado",
            ),
        ),
    ]
