# Generated by Django 5.2.8 on 2025-11-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("payments", "0005_payment_credit_note_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente registado (opcional - preencher customer_tax_id/customer_name para Consumidor Final)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="customers.customer",
                verbose_name="Cliente",
            ),
        ),
    ]
