# Generated by Django 5.2.7 on 2025-10-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='apps_profilee',
        ),
    ]
