# Generated by Django 5.2.7 on 2025-10-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='apps_profile',
        ),
    ]
