# Generated by Django 5.2.8 on 2025-11-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Número de Identificação Fiscal do cliente",
                max_length=20,
                null=True,
                verbose_name="NIF",
            ),
        ),
    ]
