# Generated by Django 5.2.8 on 2025-11-17 12:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "inventory",
            "0004_alter_inventoryitem_options_inventoryitem_created_at_and_more",
        ),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "purchaseOrderID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "po_number",
                    models.CharField(
                        help_text="Formato: OC/AAAA/NNNN (ex: OC/2025/00001)",
                        max_length=60,
                        unique=True,
                        verbose_name="Número da OC",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SUBMITTED", "Enviado ao Fornecedor"),
                            ("PARTIALLY_RECEIVED", "Parcialmente Recebido"),
                            ("RECEIVED", "Recebido"),
                            ("INVOICED", "Faturado"),
                            ("PAID", "Pago"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Data do Pedido")),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Entrega Prevista"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado Por",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="suppliers.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Compra",
                "verbose_name_plural": "Ordens de Compra",
                "db_table": "apps_purchase_order",
                "ordering": ["-order_date", "-purchaseOrderID"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantidade Pedida",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço de custo do fornecedor",
                        max_digits=10,
                        verbose_name="Preço Unitário",
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Quantidade Recebida",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Receção"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_items",
                        to="inventory.inventoryitem",
                        verbose_name="Item de Inventário",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchaseorder",
                        verbose_name="Ordem de Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Ordem de Compra",
                "verbose_name_plural": "Itens de Ordem de Compra",
                "db_table": "apps_purchase_order_item",
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "supplierInvoiceID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Número da fatura do fornecedor",
                        max_length=100,
                        verbose_name="Número da Fatura",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Data da Fatura")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor do IVA",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Total (com IVA)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recebida"),
                            ("APPROVED", "Aprovada"),
                            ("SCHEDULED_PAYMENT", "Pagamento Agendado"),
                            ("PAID", "Paga"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado Por",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional - vincular a uma OC",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices",
                        to="purchases.purchaseorder",
                        verbose_name="Ordem de Compra",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="suppliers.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura de Fornecedor",
                "verbose_name_plural": "Faturas de Fornecedores",
                "db_table": "apps_supplier_invoice",
                "ordering": ["-invoice_date", "-supplierInvoiceID"],
                "unique_together": {("supplier", "invoice_number")},
            },
        ),
    ]
