# Generated by Django 5.2.7 on 2025-10-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategory_status_menuitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='status',
        ),
        migrations.AlterModelTable(
            name='menucategory',
            table='apps_menucategory',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='apps_menuitem',
        ),
    ]
