# Generated by Django 5.2.7 on 2025-10-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('supplier', models.CharField(max_length=255)),
                ('oversell_quantity', models.IntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'apps_inventoryitem',
            },
        ),
    ]
