# Generated by Django 5.2.7 on 2025-10-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='status',
        ),
    ]
