# Generated by Django 5.2.8 on 2025-11-17 12:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_inventoryitem_status"),
        ("menu", "0003_remove_menucategory_status_remove_menuitem_status_and_more"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "ordering": ["itemName"],
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="itemName",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome do item de inventário",
                max_length=255,
                null=True,
                verbose_name="Nome do Item",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="reorder_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quando o stock atingir este nível, fazer nova encomenda",
                max_digits=10,
                null=True,
                verbose_name="Nível de Reposição",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="reorder_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantidade a encomendar quando atingir nível de reposição",
                max_digits=10,
                null=True,
                verbose_name="Quantidade de Reposição",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Último preço de custo do fornecedor",
                max_digits=10,
                verbose_name="Custo Unitário",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="menu.menuitem",
                verbose_name="Item do Menu",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="oversell_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Quantidade Vendida sem Stock",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Quantidade em Stock",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="reserved_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantidade reservada em pedidos pendentes",
                max_digits=10,
                verbose_name="Quantidade Reservada",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Fornecedor principal deste item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="suppliers.supplier",
                verbose_name="Fornecedor",
            ),
        ),
    ]
