# Generated by Django 5.2.7 on 2025-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_options_inventoryitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
