# Generated by Django 5.2.7 on 2025-10-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operationlog',
            table='apps_operationlog',
        ),
    ]
