# Generated by Django 5.2.7 on 2025-10-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modulesubscription',
            table='apps_common_module_subscription',
        ),
    ]
