# Generated by Django 5.2.8 on 2025-11-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_modulesubscription_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_registration_number",
                    models.CharField(
                        help_text="Número de Identificação Fiscal da empresa",
                        max_length=20,
                        verbose_name="NIF",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Nome da Empresa"),
                ),
                ("street_name", models.CharField(max_length=200, verbose_name="Rua")),
                (
                    "building_number",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Cidade")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Código Postal"),
                ),
                (
                    "country",
                    models.CharField(default="CV", max_length=2, verbose_name="País"),
                ),
                ("telephone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="Fax"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "fiscal_year_start_month",
                    models.IntegerField(
                        default=1,
                        help_text="1=Janeiro, 2=Fevereiro, etc.",
                        verbose_name="Mês de início do ano fiscal",
                    ),
                ),
                (
                    "invoice_series",
                    models.CharField(
                        default="FT A",
                        help_text="Ex: 'FT A', 'FT B', etc.",
                        max_length=10,
                        verbose_name="Série de Faturas",
                    ),
                ),
                (
                    "credit_note_series",
                    models.CharField(
                        default="NC A",
                        max_length=10,
                        verbose_name="Série de Notas de Crédito",
                    ),
                ),
                (
                    "receipt_series",
                    models.CharField(
                        default="TV A",
                        max_length=10,
                        verbose_name="Série de Talões de Venda",
                    ),
                ),
                (
                    "software_certificate_number",
                    models.CharField(
                        default="0",
                        help_text="Use '0' até obter a certificação oficial",
                        max_length=20,
                        verbose_name="Número de Certificado do Software",
                    ),
                ),
                (
                    "software_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=50,
                        verbose_name="Versão do Software",
                    ),
                ),
                (
                    "default_tax_code",
                    models.CharField(
                        choices=[
                            ("NOR", "Normal - 15%"),
                            ("ISE", "Isento"),
                            ("RED", "Reduzida"),
                            ("OUT", "Outro"),
                        ],
                        default="NOR",
                        max_length=10,
                        verbose_name="Código de IVA Padrão",
                    ),
                ),
                (
                    "default_tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        verbose_name="Percentagem de IVA Padrão",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
                "db_table": "apps_common_company_settings",
            },
        ),
    ]
