# Generated by Django 5.2.8 on 2025-11-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_companysettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        choices=[
                            ("NOR", "Normal"),
                            ("RED", "Reduzida"),
                            ("ISE", "Isento"),
                            ("OUT", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Código de IVA",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Ex: 'IVA Normal 15%', 'IVA Reduzido 8%'",
                        max_length=100,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ex: 15.00 para 15%",
                        max_digits=5,
                        verbose_name="Percentagem (%)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        help_text="Data de início de aplicação desta taxa",
                        verbose_name="Válido desde",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Deixe em branco se ainda estiver ativa",
                        null=True,
                        verbose_name="Válido até",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Taxa atualmente em uso",
                        verbose_name="Ativa",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "db_table": "apps_common_tax_rate",
                "ordering": ["-valid_from", "tax_code"],
                "indexes": [
                    models.Index(
                        fields=["tax_code", "valid_from"],
                        name="apps_common_tax_cod_8cec0f_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="apps_common_is_acti_6a491f_idx"
                    ),
                ],
            },
        ),
    ]
