# Generated by Django 5.2.7 on 2025-10-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operations_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operations_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operations_transfer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operations_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operations_check', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Register',
                'verbose_name_plural': 'Cash Registers',
                'db_table': 'core_cashregister',
                'ordering': ['-start_time'],
            },
        ),
    ]
