# Generated by Django 5.2.7 on 2025-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
