# Generated by Django 5.2.7 on 2025-10-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_cashregister_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='status',
        ),
        migrations.AlterModelTable(
            name='cashregister',
            table='aapps_cashregister',
        ),
    ]
