# Generated by Django 5.2.7 on 2025-10-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_remove_cashregister_status_alter_cashregister_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cashregister',
            table='apps_cashregister',
        ),
    ]
