# Generated by Django 5.2.7 on 2025-10-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableid', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('AV', 'Available'), ('OC', 'Occupied'), ('RE', 'Reserved')], default='AV', max_length=2)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'core_table',
            },
        ),
    ]
