# Generated by Django 5.2.7 on 2025-10-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='apps_tablee',
        ),
    ]
